### ISSUE TITLE
How to build the tutorial modules?

### ISSUE THREAD

**Issue by alvindizon** [SmartToolFactory/NavigationComponents-Tutorials#3]
Apologies if this is quite a basic question. But upon cloning and opening on Android Studio, it seems like only the "External-Tutorial-Navigation-Codelab" module can be built as an app. How do I build the other tutorials as separate Android apps?

**Comment by SmartToolFactory** [comment]
@alvindizon I downloaded the repo, asked me to update gradle, i'm using Android Studio 4.2 Canary 14, after updating the gradle i can see every build option on top section, and built one and it's working. I will update gradle for the project itself and commit it shortly. Would you mind checking again?

**Comment by alvindizon** [comment]
Cloning this repo on a Windows machine with Android Studio 4.0.2 and downgrading the Gradle version for both the plugin and wrapper to 4.0.1 and 6.5 respectively did the trick. I previously cloned it on a machine running macOS 10.15.7 with Android Studio 4.1 and the other modules still weren't showing up even with your latest commit, so I think this might be an Android Studio issue.

Edit: confirmed on macOS 10.15.7 with Android Studio 4.1, **downgrading** the Gradle plugin and wrapper to 4.0.1 and 6.5 respectively fixes the issue and shows the other modules properly.
