### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by raxod502** [SmartToolFactory/NavigationComponents-Tutorials#7]
Can the code from these tutorials be used in other projects under the terms of some license, such as MIT or Apache?

**Comment by SmartToolFactory** [comment]
Sure, you can use any code in this or other public repositories as you please. I add licenses to library projects, since this and other tutorials  are for educational purposes i don't add licenses, and no one asked about it, to tutorials. I or you might add any license you see fit if need be.
